name: Build

on:
  push:

permissions:
  contents: write

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Get CMake
        uses: symbitic/install-cmake@master

      - name: Get Mingw-w64
        run: sudo apt-get install mingw-w64

      - name: Configure Project
        uses: threeal/cmake-action@main
        with:
          source-dir: source
          build-dir: build
          c-compiler: x86_64-w64-mingw32-gcc
          generator: Ninja
          run-build: true

      
      - name: Add & Commit
        run: |
          git config --global user.name "Actions"
          git clean -d -f -x
          git add .
          git commit --allow-empty-message --no-edit
          git push