name: Build
on:
  push:
  
permissions:
  contents: write
    
jobs:
  build-project:
    name: Build Project
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Get CMake
        uses: symbitic/install-cmake@master

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          source-dir: source
          build-dir: build
          c-compiler: gcc
          generator: Ninja
      
      - name: Add & Commit
        run: |
          git config --global user.name "Actions"
          git add .
          git commit --allow-empty-message --no-edit
          git push
