name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Get CMake
        uses: symbitic/install-cmake@master

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          source-dir: source
          build-dir: build
          c-compiler: gcc
          generator: Ninja
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.4
        with:
          push: --repo=https://Havael2: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@github.com/agapethos/MegaAutoDinos.git --set-upstream