name: Build
on:
  push:
  
permissions: write-all
    
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Get CMake
        uses: symbitic/install-cmake@master

      - name: Get Mingw-w64
        run: bash ${GITHUB_WORKSPACE}/mingw.sh

      - name: Configure Project
        uses: threeal/cmake-action@main
        with:
          source-dir: source
          build-dir: build
          c-compiler: ${GITHUB_WORKSPACE}/BUILDROOT/gcc
          generator: Ninja
          run-build: false
          args: --clean-first

      - name: Build Project
        run: "gcc -b x86_64-pc-mingw32"
      
      - name: Add & Commit
        run: |
          git config --global user.name "Actions"
          git add .
          git commit --allow-empty-message --no-edit
          git push
