name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Get CMake
        uses: symbitic/install-cmake@master

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          sources-dir: megaAutoDinos.c
          generator: Ninja
          compiler: gcc
          
