name: Build
on:
  push:
  
permissions:
  contents: write
    
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Get mingw-w64
        run: |
          sudo apt-get install mingw-w64

      - name: install-cmake
        uses: Symbitic/install-cmake@v0.1.0

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          source-dir: source
          build-dir: build
          c-compiler: x86_64-w64-mingw32-gcc
          generator: Ninja

      - name: Clean
        run: |
          ninja clean
      
      - name: Add & Commit
        run: |
          git config --global user.name "Actions"
          git add .
          git commit --allow-empty-message --no-edit
          git push
