name: Create Release

on:
  push:
    branches:
      - master  # Or specify your main branch here

permissions:
    deployments: write
    contents: read

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/build/MegaAutoDinos.exe
          prerelease: true

