name: Attach File to Release

on:
  release:
    types: [created]

permissions:
    deployments: write
    contents: read

jobs:
  attach-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Attach File to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/MegaAutoDinos.exe
          asset_name: MegaAutoDinos.exe
          asset_content_type: application/octet-stream