name: Create Release

on:
  push:
    branches:
      - main  # Or specify your main branch here

permissions:
    deployments: write
    contents: read

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/MegaAutoDinos.exe
          tag_name: v1.0.0  # Replace with your desired tag version
          release_name: Release v1.0.0  # Replace with your desired release name
          body: |
            Describe your release here
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

